from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.opc.constants import RELATIONSHIP_TYPE as RT
from pathlib import Path
out=Path('/Users/sushil/Documents/JTSC/meet-guide')
d=Document(); s=d.sections[0]; s.page_width=Inches(8.5); s.page_height=Inches(11)
s.top_margin=s.bottom_margin=Inches(.65); s.left_margin=s.right_margin=Inches(.75)
for name in ['Normal','Title','Subtitle','Heading 1','Heading 2']:
 st=d.styles[name]; st.font.name='Calibri'; st.font.color.rgb=RGBColor(0,0,0)
 st.paragraph_format.space_after=Pt(7)
d.styles['Caption'].font.color.rgb=RGBColor(0,0,0)
d.styles['Caption'].font.bold=False
for el in d.styles.element.iter():
 for child in list(el):
  if child.tag == qn('w:pBdr'): el.remove(child)
d.styles['Normal'].font.size=Pt(11); d.styles['Normal'].paragraph_format.line_spacing=1.08
d.styles['Title'].font.size=Pt(26); d.styles['Heading 1'].font.size=Pt(20); d.styles['Heading 2'].font.size=Pt(13)
h=s.header.paragraphs[0]; h.text='QUANTUM SWIMMING  |  TEAM MEET GUIDE'; h.style='Caption'; h.runs[0].font.color.rgb=RGBColor(0,0,0)
f=s.footer.paragraphs[0]; f.text='Team tutorial  •  Based on Swiss Timing manual v1.4   |   '
f.runs[0].font.size=Pt(9); fld=OxmlElement('w:fldSimple'); fld.set(qn('w:instr'),'PAGE'); f._p.append(fld)
def p(t='',style=None): return d.add_paragraph(t,style)
def head(t): d.add_heading(t,2)
def step(n,title,text):
 x=p(); x.add_run(f'{n}  {title}. ').bold=True; x.add_run(text)
def check(t): p('[ ]  '+t)
def page(title,ref):
 d.add_page_break(); d.add_heading(title,1); p(ref,'Subtitle')
def link(label,url):
 x=p(); h=OxmlElement('w:hyperlink'); h.set(qn('r:id'),x.part.relate_to(url,RT.HYPERLINK,is_external=True)); r=OxmlElement('w:r'); pr=OxmlElement('w:rPr'); c=OxmlElement('w:color'); c.set(qn('w:val'),'0563C1'); pr.append(c); r.append(pr); t=OxmlElement('w:t'); t.text=label; r.append(t); h.append(r); x._p.append(h)
d.add_heading('Run a swim meet with Quantum',0)
p('A practical tutorial for the timing team','Subtitle')
p('Use this guide to prepare Quantum Swimming, time each heat, check the results, and finish the session. Read it once with your timing lead, then keep page 6 beside the computer during the meet.')
p('The routine is simple: open the correct heat, confirm readiness, watch the race, review the result, mark it official, and move to the next heat.')
head('Start here')
step(1,'Connect and test','Prepare the timer, pool equipment and results connection. See page 2.')
step(2,'Load the session','Import or build the schedule and verify swimmers and lanes. See page 3.')
step(3,'Run each heat','Use the same checks before and after every race. See page 4.')
step(4,'Handle exceptions','Use the recovery steps on page 5 with the timing lead.')
step(5,'Close the session','Use the final checklist on page 6.')
head('Agree who does what')
p('Suggested team roles: the timing operator runs Quantum; the results operator checks the meet-management system and receives results; the deck helper tests pads and buttons. The starter and referee handle race decisions. A small team may combine roles.')
head('Know these terms')
p('Event: the race category, such as 100 freestyle. Heat: one group swimming that event. Start list: swimmers assigned to lanes. DH: the data-handling connection to meet-management software. SCB: the scoreboard connection. Official: Quantum’s reviewed-result status, which may also trigger printing or export.')
head('About this guide')
p('Based on QUANTUM-SWIMMING User’s Manual 3480.509.02, version 1.4, October 2019. Menu labels and icons may differ in your installed version. This guide assumes the equipment is installed; the manual refers hardware installation to Quantum Concept 3480.508.02. Team roles, practice drills and sign-off checks are suggested operating practices.')
link('Open the original Swiss Timing manual','https://www.swisstiming.com/fileadmin/Resources/Instruction_Manuals/3480.509.02_AQU_Quantum_SW_User_Manual.pdf')
p('References below use the manual’s printed page numbers. Add 6 to find the PDF page number.', 'Caption')
page('1  Prepare and test the system','Manual reference  |  pages 5 to 7 and 10 to 20')
step(1,'Connect the equipment','Have the timing lead verify the start system, harnesses, touchpads, backup buttons, laptop, timer, scoreboard and results connection. Use approved power equipment and keep electronics protected from splashes. Connect the USB protection dongle; racing requires it.')
step(2,'Open Quantum Swimming','Check the Home screen timer indicator. Green means connected; red means disconnected. In Configuration > Timer, use Auto for the USB serial port. It can take about 10 seconds, or more than a minute on the first connection.')
step(3,'Synchronize the timer','For one timer, select PC time or enter a manual time, then use Do synchro. With primary and secondary timers, use On Start Pulse: connect and power the start device, enter the same desired time on both, press Do synchro on both, then send a start pulse. Send a test pulse after the ready light returns to verify synchronization.')
step(4,'Create or open the session','From Home, choose Race. Create a clearly named meet without special characters, such as ClubMeetS1. The manual recommends one Quantum meet per session. Double-click an existing meet to open it.')
step(5,'Set the pool before loading races','In Pool Configuration, match the actual pool length, finish side, lane count and order, module-to-lane mapping, and connected devices at each end. A green module number means it is communicating. Do not assume a saved setup matches today’s pool.')
step(6,'Test every connected input','Open Pool test. Have a helper touch each pad and press each backup button separately, at each equipped end. Confirm the correct lane and device counter increases. Test platforms if fitted. Clear totals before a final check after warm-up. Resolve missing signals or wrong-lane signals before racing.')
step(7,'Review timing and output settings','Have the timing lead check arming delays, start arming delay, warning settings, printers and I/Os. Arming delays must suit your swimmers and pool; do not copy a generic number. Enable the I/O checkboxes for the outputs you use.')
head('Ready to load the schedule')
check('Timer connected and synchronized; required modules communicate.')
check('Pool configuration matches the physical setup; every input tested.')
check('Battery levels, printer paper and the backup timing arrangements checked.')
p('Pool length note: the manual shows 25 m and 50 m options. For a different length or a yards pool, have the timing lead verify the supported configuration before entering races.', 'Caption')
page('2  Load and rehearse the session','Manual reference  |  pages 12 to 15 and 20 to 22')
head('If you use meet management software')
step(1,'Set up the DH connection','In I/Os, select the interface used by your results team, enter its folder or connection settings, and enable its checkbox. Agree the exact shared folder and session with the results operator.')
step(2,'Import the schedule','Click the DH button above the workspace and choose Import schedule. Check the three Schedule areas: events, heats, and swimmers assigned to lanes. If needed, use the DH dashboard’s import-start-lists action.')
step(3,'Compare with the meet program','Verify event numbers, distances, strokes, rounds, heat counts and lane assignments. Confirm scratches and changes with the results team. An empty name can make a lane unused when Auto unused lanes is enabled.')
head('HY TEK setup if your team uses it')
p('Choose DH_HYTEK. Set the shared-folder path and the HYTEK Data Set number agreed with the results operator. The manual specifies quantum.sch for the schedule, startlist.slx for start lists, and *.qaq files for exported results. Confirm your HY-TEK version supports this exchange and test both directions before the meet.')
p('Other supported workflows in the manual include DH_LSTFILES and DH_SPLASH. Their settings differ. Use your venue’s tested setup; the HY-TEK filenames do not apply to every interface.')
head('If you enter the schedule manually')
step(1,'Add events','On Schedule, use the add-event button and complete the event details. Check distance, stroke, category and round. Use the edit-event control to correct details.')
step(2,'Add heats','Select an event and use the add-heat button once per heat needed.')
step(3,'Assign swimmers','Double-click a lane in the swimmer area to open Add Swimmer. Find or create the swimmer, choose the lane, then click Add to Startlist. For relays, Display relays lets you add team members in swimming order.')
head('Run a short practice before the first session')
p('Suggested drill: use a separate practice meet and a test results folder or data set agreed with the results operator. Open a heat, confirm the ready light, send a start and simulate touches in the correct order after the arming delays. Check finish times, practice reviewing a backup time, mark the test official and confirm delivery to the results team.')
p('Return to the real session afterward. Recheck the selected meet, pool setup, schedule, outputs and first heat. Tell the starter when the real session is ready.')
page('3  Run every heat the same way','Manual reference  |  pages 23 to 31')
head('Before the start')
step(1,'Open the correct heat','On Schedule, select the event and double-click the heat. Read the event number, heat number and distance aloud with your partner. Check swimmers, active lanes and the expected finish end.')
step(2,'Confirm readiness','Start armed should be green and checked. The connected start input should be green, and the starter should have the ready light. A connected scoreboard should show 0.00. If an authorized official asks you to hold, click Start armed to disarm it; re-arm only when cleared.')
head('While swimmers are racing')
step(3,'Confirm the race clock is running','After the start signal, check that timing began. Click the timing-window focus button: its frame should be yellow so keyboard shortcuts work. A red frame means shortcuts may not reach this window.')
step(4,'Watch the lanes','Follow touches, distance completed, direction and finish indicators. Compare the display with what is happening in the pool. Check a missing touch or unexpected finish with your timing lead. Keep the harness connection active; its disconnect control blocks incoming timing pulses.')
head('After the finish')
step(5,'Review every lane','Open or check Result view. Confirm you are reviewing this event and heat, especially if the timing and result windows have been unlinked. Check the final distance, finish times, missing results and backup-time differences. Confirm DNS (did not start), DNF (did not finish) or DSQ (disqualified) with the appropriate official.')
step(6,'Resolve questions before making it official','Check questionable pad times against recorded backups and the officials’ decision. Quantum’s backup-difference indicators include 200 ms comparisons; these are review cues, not instructions to replace a result automatically. Record any correction and its reason.')
step(7,'Mark the heat official','Once review is complete, click the result’s official control. Depending on enabled settings, this can print results, change the scoreboard and export results. Check the intended output, and have the results operator confirm receipt. Use the DH export action if your configured workflow requires it.')
step(8,'Advance to the next heat','Use Next heat or Ctrl+N. It advances to the next event after the last heat. If Quantum warns that the race is unfinished or unofficial, resolve the warning before continuing. Repeat the event, heat and distance check.')
head('Simple team callouts')
p('Before: “Event 12, heat 3, 100 freestyle. Lanes checked. Ready.”\nAfter: “All lanes reviewed. Results confirmed. Official. Next heat.”')
page('4  Fix common problems','Manual reference  |  pages 5 to 9 and 23 to 31')
head('The timer indicator is red')
p('Check timer power and the USB connection. Return to Configuration > Timer and check Auto or the correct serial port. Allow the connection time described on page 2. If it remains disconnected, ask the timing lead to troubleshoot; do not start the next heat until timing readiness is restored.')
head('A genuine start happened while Quantum was unarmed')
p('Open the correct heat if needed. Inspect the time shown beneath Attrib last start. If it is the genuine start, use that button to apply it. The adjacent arrow lists other recorded unarmed starts. Have the timing lead identify the correct signal; a later test pulse must not become the race start.')
head('The officials recall a start after the clock begins')
p('On the officials’ instruction, use Arm start to reset timing for another start. Confirm the correct heat and the ready light again. Do not reset a valid race to fix a missed start; use the recorded-start recovery above.')
head('A pad touch or finish is missing')
p('Identify the lane and expected end. Check whether its module is communicating and whether its pad was armed. The backup-time button, when shown, or B in the lane menu takes the recorded backup time. Review the evidence and apply the meet’s approved timing procedure with the officials before making the result official.')
head('A lane shows the wrong lap or distance progress')
p('Click that lane number to open its menu. After checking the actual swim, use the add-lap or remove-lap control as needed. Recheck distance and the expected next touch. The white control above the lane buttons can apply changes to all swimmers, so use it only when the same correction is required for every lane.')
head('A lane needs to be armed or marked unused')
p('Use its lane menu or pad-arm indicator. In the lane menu, Q arms, Y disarms and U toggles used/unused on the manual’s US keyboard layout. Verify the selected lane before acting. A missing name can automatically mark a lane unused; confirm against the start list.')
head('The scoreboard or results computer is not updating')
p('Check that the relevant I/O checkbox is enabled, then check the selected output, port or shared-folder path with the results operator. Confirm which heat is displayed in Result view before sending results. Use the dashboard’s scoreboard refresh or DH export action as appropriate, then verify the destination.')
head('The dongle is missing or shortcuts do not respond')
p('Dongle: check that the USB protection key is connected; without it, races cannot start. Ask the timing lead for the licensing procedure in manual section 4.3.1. Shortcuts: first give the timing window focus and confirm a yellow frame. Use visible controls if your keyboard mapping differs.')
page('5  Keep this beside the timing computer','Quick checklist and session handoff')
head('Before the first heat')
for t in ['Correct meet and session open; timer connected and synchronized.', 'Pool configured before schedule import; all pads and buttons tested.', 'Schedule, names, lanes and distances checked against the meet program.', 'Starter, scoreboard, results transfer and backup timing tested.']: check(t)
head('Every heat')
for t in ['Open and verify the event, heat, distance, lanes and finish end.', 'Confirm Start armed, the connected start input and starter ready light.', 'After the start, check the running clock and give the timing window focus.', 'Watch touches and distance progress; investigate missing or extra touches.', 'Review the correct heat and final-distance results with the results team.', 'Resolve corrections, mark official and confirm export or print as needed.', 'Select Next heat and repeat the pre-start check.']: check(t)
head('At the end of the session')
for t in ['Check for unfinished or unofficial heats and resolve them with officials.', 'Confirm the results team has all final results and corrections.', 'Close the race window and exit through Home > Quit when work is complete.', 'Recommended: copy the session data and exchanged result files to the team’s backup location and verify the copy.', 'Hand off unresolved equipment issues and use the equipment care procedures.']: check(t)
p('The manual’s usual data location is %stDrcApp%\\Quantum\\Swimming\\Data\\[meet name]. Have the timing lead locate the actual folder on your computer. Touchpads should be cleaned with fresh water and a cloth, dried naturally and stored vertically. Follow each product’s instructions for the rest of the equipment.', 'Caption')
head('Heat status and useful controls')
p('I = Idle   |   W = Waiting for start   |   S = Started\nF = Finished but not official   |   O = Official   |   U = Unfinished')
p('Ctrl+N = Next heat. Click a lane number to open its menu. In that menu, B = backup time, Q = arm pad, Y = disarm pad. These shortcuts use the manual’s US keyboard layout and require timing-window focus.')
p('Meet and session ____________________   Timing lead ____________________\nResults operator ____________________   Backup location ____________________')
p('Manual references: data folder p. 20; shutdown p. 5; equipment care pp. 33-34; status and shortcuts pp. 35-36.', 'Caption')
d.save(out/'Quantum_Swimming_Team_Tutorial.docx')
